version: '3'

services:
  service1:
    build:
      context: ./service1
    ports:
      - '3001:3000'
    environment:
      - SERVICE1_ENV=development
      - SERVICE2_URI=http://service2:3000

  service2:
    build:
      context: ./service2
    ports:
      - '3002:3000'
    environment:
      - SERVICE2_ENV=development
# docker-compose up
# docker-compose up --scale service1=3
